name: Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  run-build:
    uses: "oezcan-guezelsarslan/cicdtemplates/.github/workflows/ci.yml@v1.6.0"
    with:
      target-branch: ${{ github.head_ref || github.ref_name }}
    permissions:
      contents: write
      packages: write
      security-events: write
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
